# Generated by Django 2.0.3 on 2018-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_auto_20170616_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='reviewed',
            field=models.NullBooleanField(),
        ),
        migrations.RunSQL("UPDATE proctoring_exam SET reviewed = IF(reviewed_exam = 'True', 1, 0);"),
        migrations.RemoveField(
            model_name='exam',
            name='reviewed_exam',
        ),
    ]
