# Generated by Django 2.0.3 on 2018-03-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_reviewed_bool_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='attempt_status_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
