# Generated by Django 2.0.3 on 2018-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0005_auto_20180323_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=255, verbose_name='slug')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Organization description',
                'verbose_name_plural': 'Organization descriptions',
            },
        ),
        migrations.AlterField(
            model_name='eventsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('archived', 'Archived')], default='in_progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('new', 'Not started'), ('finished', 'Finished'), ('failed', 'Failed'), ('started', 'Started')], default='new', max_length=8),
        ),
    ]
