# Generated by Django 2.0.3 on 2018-04-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0007_update_comment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='exam_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
