# Generated by Django 2.0.3 on 2018-05-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0008_update_exam_name_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.TextField(blank=False, null=False),
        ),
    ]
